name: Linux

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: ./src/scripts/build.sh
    - name: Artifact
      uses: actions/upload-artifact@v4
      with:
        name: friction-ci-linux-x86_64
        path: |
          distfiles/builds/*/*.rpm
          distfiles/builds/*/*.xz
          distfiles/builds/*/*.AppImage
